export interface Page {
  slug: string;
  title: string;
}

export const pages: Page[] = [
  { slug: 'home', title: 'ארגון יוצאי ביאליסטוק והסביבה בישראל' },
  { slug: 'about', title: 'About' },
  { slug: 'about-1', title: 'טכס אזכרה ה-80, 24.8.23, ביהוד' },
  { slug: 'contact', title: 'Contact' },
  { slug: 'news', title: 'News' },
  { slug: 'blog', title: 'Blog' },
  { slug: 'gallery', title: 'Gallery' },
  { slug: 'videos', title: 'Videos' },
  { slug: 'programs', title: 'Programs' },
  { slug: 'get-involved', title: 'Get Involved' },
  { slug: 'organization-goals', title: 'מטרות העמותה' },
  { slug: 'organization-structure', title: 'מבנה אירגוני' },
  { slug: 'city-history', title: 'תולדות יהודי ביאליסטוק' },
  { slug: 'related-sites', title: 'אתרים קשורים' },
  { slug: 'famous-people', title: 'אישים מביאליסטוק' },
  { slug: 'yitzhak-shamir', title: 'יצחק שמיר' },
  { slug: 'nachum-zemach', title: 'נחום צמח' },
  { slug: 'moshe-chassid', title: 'משה חסיד' },
  { slug: 'dr-zamenhof', title: 'ד"ר לודויג זמנהוף' },
  { slug: 'mordechai-tenenbaum', title: 'מרדכי טננבוים' },
  { slug: 'yitzhak-melamed', title: 'יצחק מלמד' },
  { slug: 'yosef-chazanovitz', title: 'ד״ר יוסף חזנוביץ' },
  { slug: 'rabbi-mohilever', title: 'הרב שמואל מוהליבר' },
  { slug: 'shmuel-pisar', title: 'שמואל פיזאר' },
  { slug: 'elazar-sukenik', title: 'פרופסור אלעזר ליפא סוקניק' },
  { slug: 'sukenik-copy', title: 'אלפרט' },
  { slug: 'shlomo-kaplansky', title: 'שלמה קפלנסקי' },
  { slug: 'past-ceremonies', title: 'טכסי אזכרה קודמים' },
  { slug: 'ceremony-2022', title: 'טכס אזכרה ה-79, 18.8.22, ביהוד' },
  { slug: 'ceremony-2023-poland', title: 'אזכרה 5.2.23 בביאליסטוק, פולין' },
  { slug: 'ceremony-80th', title: 'טכס אזכרה ה-80, 16.8.23, בביאליסטוק' },
  { slug: 'ceremony-74th', title: 'טכס יום השואה 2014 + 2017' },
  { slug: 'ceremony-81st', title: 'טכס אזכרה ה-81, 29.8.24, ביהוד' },
  { slug: 'ceremony-82nd', title: 'טכס אזכרה ה-82, 21.8.25 ביהוד' },
  { slug: 'kiryat-bialystok-milestones', title: 'ציוני דרך בתולדות הקרייה והעמותה' },
  { slug: 'jewish-museum-bialystok', title: 'המוזאון היהודי בביאליסטוק' },
  { slug: 'cemetery-restoration', title: 'בית הקברות היהודי בביאליסטוק' },
  { slug: 'scientific-conference-2010', title: 'כנס מדעי "ביאליסטוק כמודל" 11.2010' },
  { slug: 'torah-scroll-2016', title: 'הכנסת ספר תורה 10.2016' },
  { slug: 'memorial-book', title: 'ספר זיכרון לביאליסטוק' },
  { slug: 'bialystok-map', title: 'מפות ביאליסטוק והגטו' },
  { slug: 'blank', title: 'Blank' },
];
